[package]
name = "dive"
version = "0.1.0"
edition = "2018"

[dependencies]
# Rendering
vulkano = "^0.24"
vulkano-shaders = "^0.24"
vulkano-win = "^0.24"
winit = "^0.25"
genmesh = "^0.6"
# Math
nalgebra-glm = "^0.13"